USE [master]
GO

/****** Object:  Database [COMPANY]    Script Date: 2024/12/23 17:15:17 ******/
CREATE DATABASE [COMPANY]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COMPANY', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\COMPANY.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'COMPANY_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\COMPANY_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COMPANY].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [COMPANY] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [COMPANY] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [COMPANY] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [COMPANY] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [COMPANY] SET ARITHABORT OFF 
GO

ALTER DATABASE [COMPANY] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [COMPANY] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [COMPANY] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [COMPANY] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [COMPANY] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [COMPANY] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [COMPANY] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [COMPANY] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [COMPANY] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [COMPANY] SET  DISABLE_BROKER 
GO

ALTER DATABASE [COMPANY] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [COMPANY] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [COMPANY] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [COMPANY] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [COMPANY] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [COMPANY] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [COMPANY] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [COMPANY] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [COMPANY] SET  MULTI_USER 
GO

ALTER DATABASE [COMPANY] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [COMPANY] SET DB_CHAINING OFF 
GO

ALTER DATABASE [COMPANY] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [COMPANY] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [COMPANY] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [COMPANY] SET QUERY_STORE = OFF
GO

ALTER DATABASE [COMPANY] SET  READ_WRITE 
GO

